---
title: "Tarea 1"
author: |
        | Teoría del Riesgo 2022-1
output: pdf_document
header-includes:
- \usepackage{enumitem}  
- \usepackage{caption}
- \usepackage{amsmath}
- \captionsetup{labelformat=empty}
---

```{r setup,echo=F}
knitr::opts_chunk$set(echo=T, message=FALSE, warning=FALSE, 
                      out.width='100%', fig.align='center', eval=T)
```

Realiza los siguientes ejercicios cuidando el formato y las reglas establecidas en la presentación del curso. Sube las soluciones a *Classroom* dentro del apartado correspondiente a esta tarea en archivos **NO COMRPIMIDOS**.
\newline

**Ejercicio 1.**
\newline

Suponiendo que $\hat{\theta}=(\hat{\theta}_1,...,\hat{\theta}_n)$ con $n\geq 0$, es un estimador máximo verosímil para el parámetro $\theta = ( \theta_1,...,\theta_n)$. Sea $\tau$ una función de $\theta$, demuestre que $\hat{\tau(\theta)}$ es estimador máximo verosímil de $\tau(\theta)$.
\newline

Detalla cada uno de los pasos en tu demostración.
\newline

**Ejercicio 2.**
\newline

Se define como una medida de riesgo $\rho$ como una función de variables aleatorias a los reales que cumple las siguientes 3 propiedades:
\begin{enumerate}
\item[a)]$\rho(\bar{0}) = 0$ donde $\bar{0}$ es la variable aleatoria que vale cero en todo el espacio muestra.
\item[b)] Para toda $a \in R$ y $X$ v.a., se tiene que $\rho(X + a) = \rho(X) +a$.
         
\item[c)] Para cuales quiera $X,Y$ v.a.´s. Si $X \leq Y$ en el sentido de que todos los valores de $X$ son menores a los de $Y$, entonces $\rho(X) \leq \rho(Y)$.
\end{enumerate}
Con esta definición demuestre que $VaR$ y $TVaR$ son medidas de riesgo. Por otro lado, encuentre alguna función de variables aleatorias que $\mathbf{no}$ sea medida de riesgo argumentando tu respuesta debidamente.
\newline

**Ejercicio 3.**
\newline

Sean $X_1\sim exp\left(\frac{1}{100}\right)$ y $X_2\sim exp\left(\frac{1}{200}\right)$ las v.a. que modelan dos riesgos independientes. Calcular 
\begin{enumerate}
\item[a)] $VaR_0.9(X_1+X_2)$ de forma teórica y de forma muestral usando $10,000$ simulaciones.
\item[b)] $VaR_{0.95}(X_1+X_2)$ de forma teórica y de forma muestral usando $10,000$ simulaciones.
\end{enumerate}
${}$
\newpage

**Ejercicio 4.**
\newline

Haciendo uso de la definición de $VaR_p\left ( X \right )$ y $TVaR_p\left ( X \right )$ 
\begin{enumerate}
\item[a)] obten la formula general suponiendo que $X\sim Pareto\left ( a,b \right )$
\item[b)] Supongamos que las pérdidas anuales $X\sim Pareto\left ( a,b \right )$, además sabemos:

i) $\mathbb{E}\left [ X \right ]=100$

ii) $Var\left [ X \right ]=20,000$

\end{enumerate}
Usando el inciso a) calcula el $VaR_p\left ( X \right )$ y $TVaR_p\left ( X \right )$ con un nivel de confianza del 65%
${}$\newline

**Ejercicio 5.**
\newline

Sea $X_1,..,X_n$ una muestra de $v.a.i.i.d.$ con distribución Uniforme$(\theta_1,\theta_2)$ con $\theta_1<\theta_2$, dadas las constantes de normalización $a_n$ y $b_n$, sabemos que: la distribución de valores extremos a la que converge es una distribución $$Weibull(\theta_2-\theta_1,0,1)$$
\begin{enumerate}
\item[a)] Determine los valores de $a_n$ y $b_n$.
\end{enumerate}
${}$\newline


**Ejercicio 6.**
\newline

Sea $X_1,...,X_n$ una muestra de v.a.i.i.d con distribución exponencial con media $\frac{1}{\lambda}$.
\begin{enumerate}
\item[a)] Determinar las constantes $a_n$ y $b_n$ tales que la distribución de valores extremos converga a una distribución Gumbel con parámetros $\alpha=\frac{1}{\lambda}$ y $\beta=0$.
\item[b)] Para un valor de $\lambda$ (ustedes pueden elegirlo), simular una muestra lo suficientemente grande para que las 3 pruebas de bondad de ajuste vistas en clase concluyan que proviene de la distribución deseada. Comparar la función de distribución de valores extremos teórica y la función de distribución empírica.
\end{enumerate}
${}$\newline


**Ejercicio 7.**
\newline

Para una distribución de clase $\left ( a,b,0 \right )$ 
\begin{enumerate}
\item[a)] Determina la media de la distribución haciendo uso de la siguiente información:
\begin{enumerate}
\item[i)] $P_k=0.0768$
\item[ii)] $P_{k+1}=P_{k+2}=0.08192$
\item[iii)] $P_{k+3}=0.078432$
\end{enumerate}
\end{enumerate}
${}$\newline
\newpage

**Ejercicio 8.**
\newline

En el archivo \textbf{NumeroReclamos.csv} contiene el historial del número de reclamos mensuales que tiene una aseguradora. Suponiendo que la distribución de dicha muestra pertenece a la clase $(a,b,0)$,
\begin{enumerate}
\item[a)] Proponga una distirbución que se ajuste a la frecuencia. Justifica tu respuesta.
\item[b)] Dado el inciso anterior, estimar los parámetros asociados a la distribución propuesta y posteriormente calcular los parámetros $a$ y $b$.
\item[c)] Compara las probabilidades empíricas de la muestra con las probabilidades de la distribución ajustada para los puntos $45,41,...,55$. ¿cuál es la diferencia más grande?¿cómo se podría reducir dicho error?  
\end{enumerate}
${}$\newline


**Ejercicio 9.**
\newline
Sea $N$ una v.a. con distribución de probabilidad de clase $(a,b,0)$. A partir de la definición clásica de esperanza, demuestre que
$$E(N) = \frac{a+b}{1-a}$$

${}$\newline


**Ejercicio 10.**
\newline

Para una distribución de clase $\left ( a,b,0 \right )$ tenemos:
\begin{enumerate}
\item[i)] $\frac{P_2}{P_1}=0.25$
\item[ii)] $\frac{P_4}{P_3}=0.225$
\end{enumerate}
${}$\newline
a) Encuentra el valor de $P_2$
